---
version: "3.5"

networks:
  default:
    driver: bridge
    name: lab

services:
  gitlab:
    container_name: gitlab
    environment:
      # These settings will be evaluated on load - see
      # https://docs.gitlab.com/omnibus/docker/#pre-configure-docker-container
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = '12345678';
        external_url "http://gitlab.demo.local/";
        prometheus_monitoring['enable'] = false;
    image: gitlab/gitlab-ce
    networks:
      default:
        aliases:
          - gitlab.demo.local
    ports:
      - "80:80"
      - "7722:22"
    restart: unless-stopped
    stop_grace_period: 10m
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab

  jenkins:
    container_name: jenkins
    environment:
      - JENKINS_OPTS=--httpPort=8080
    image: jenkinsci/blueocean
    privileged: true
    networks:
      default:
        aliases:
          - jenkins.demo.local
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /etc/passwd:/etc/passwd:ro # Ensure that user can be found/mapped
      - /home/jenkins:/home/jenkins:rw # Enables the jenkins user to write .ssh/known_hosts
      - /var/jenkins_home:/var/jenkins_home:rw # Workspace home
      - /var/run/docker.sock:/var/run/docker.sock:ro # Allows Jenkins to stop/start containers

  registry:
    container_name: registry
    image: registry:2
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - registry.demo.local
    volumes:
      - registry:/var/lib/registry
  
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.1-community
    networks:
      default:
        aliases:
          - sonarqube.demo.local
    ports:
      - "9000:9000"
    restart: unless-stopped
    stop_grace_period: 10m
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

volumes:
  gitlab_config:
  gitlab_data:
  gitlab_logs:
  registry:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
    driver_opts:
      type: tmpfs
      device: tmpfs
